config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"
  
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
    @button_text = "Create Article"
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @article = Article.find(params[:id])
    @button_text = "Edit Article"
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def truncate_text(text)
    truncate(text, length: 250, separator: "...")
  end

  def publication_date(e)
    e.strftime("%B %e,%Y")
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="article-title-form">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message_error| %>
      <div class='input-error-message'><%= message_error %></div>
    <% end %>
  </div>
  
  <div class="article-body-form">
    <%= form.label :body %>
    <%= form.text_area :body %>
    <% article.errors.full_messages_for(:body).each do |message_error| %>
      <div class='input-error-message'><%= message_error %></div>
    <% end %>
  </div>

  <div class="article-status-form">
    <%= form.label :status %>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div class="btn-submit-container">
    <%= form.submit @button_text, class: "btn-submit" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="bg-green">
  <div class="new-edit-article-container" >
    <h1>Edit Article</h1>
    <%= render "form", article: @article%>
  </div>
</div>

app/views/articles/index.html.erb
<div class="blog-title-container">
  <h1>Articles</h1>
  <%= link_to "New Article", new_article_path, class:"new-article" %>
</div>

<h3 class="article-counter">Our blog has <%= Article.public_count %> articles and counting!</h3>

<div class="articles-container">
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <div class="article">
        <h4 class="index-article-date"><%= publication_date(article.created_at) %></h4>

        <dl>
          <dt class="index-article-title"><%= link_to article.title, article %></dt>
          <dd class="index-article-body"><%= truncate_text(article.body)%></dd>
        </dl>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="bg-green">
  <div class="new-edit-article-container" >
    <h1>New Article</h1>
    <%= render "form", article: @article%>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article-show">
  <div class= "article-links">
    <ul class= "article-links-list">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Edit Article", edit_article_path(@article) %></li>
      <li><%= link_to "Destroy", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
    </ul>
  </div>

  <div class="article-container-show">
    <div class="article-texts">
      <h1><%= @article.title%></h1>
      <h4 class="index-article-date">Autor, <%= publication_date(@article.created_at) %></h4>
      <p><%= simple_format(@article.body)%></p>
    </div>

    <div class="article-comments-container">
      <h2>Add a comment:</h2>
      <%= render 'comments/form' %>

      <h2>Comments</h2>
      <% if @article.comments.count.zero? %>
        <p>There are no comments to display</p>
      <% else %>
        <%= render @article.comments.reject(&:new_record?) %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
  <p>
    <%= link_to "Editar Comentário", edit_article_comment_path(@article, comment.id) if comment.persisted? %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<div class="form-comment">
  <%= form_with model: [@article, @comment || @article.comments.build] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>

    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>

    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>

    <p class="btn-comment">
      <%= form.submit @button_text, class: "btn-submit" %>
    </p>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", article: @article, comment: @comment %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'MyBLog', root_path%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="container-links">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %> 
        <% else %>
          <%= link_to "Sign in", new_user_session_path %> 
          <%= link_to "Sign up", new_user_registration_path %><br />
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>